// DiccioPeques — Edge Function: Share URL Handler
// Crawlers: HTML with OG tags (og:image points to og-image function for PNG)
// Users: HTTP 302 redirect to the app

const SB_URL = Deno.env.get('SB_URL') ?? ''
const SB_ANON_KEY = Deno.env.get('SB_ANON_KEY') ?? ''
const APP_URL = 'https://nsorribas.github.io/Dicciopeques/'
const FUNCTION_URL = 'https://leivaafvepovjrkzntxr.supabase.co/functions/v1/share'
const OG_IMAGE_URL = 'https://leivaafvepovjrkzntxr.supabase.co/functions/v1/og-image'

// --- Crawler detection ---
const CRAWLER_SUBSTRINGS = [
  'facebookexternalhit', 'Facebot', 'facebookbot',
  'Twitterbot', 'twittercard',
  'linkedinbot', 'LinkedInApp',
  'WhatsApp', 'WhatsAppBot',
  'TelegramBot', 'telegram',
  'discordbot', 'Discord',
  'Slackbot', 'Slack-LinkExpanding',
  'Googlebot', 'bingbot',
  'opengraph', 'og-scraper',
  'validator', 'debugger',
  'bot', 'crawler', 'spider',
  'scrape', 'preview',
  'SkypeUriPreview', 'Pinterestbot', 'redditbot',
]

function isCrawler(userAgent: string): boolean {
  const ua = userAgent.toLowerCase()
  if (ua.includes('mozilla/') && !ua.includes('bot') && !ua.includes('crawler') && !ua.includes('spider')) {
    return false
  }
  return CRAWLER_SUBSTRINGS.some(p => ua.includes(p.toLowerCase()))
}

// --- Fetch word from Supabase ---
async function fetchWord(word: string) {
  try {
    const res = await fetch(
      `${SB_URL}/rest/v1/palabras?palabra=eq.${encodeURIComponent(word)}&select=palabra,categoria,definiciones(numero,texto)&definiciones.order=numero.asc&limit=1`,
      {
        headers: {
          apikey: SB_ANON_KEY,
          Authorization: `Bearer ${SB_ANON_KEY}`
        }
      }
    )
    const data = await res.json()
    if (data && data.length > 0) return data[0]
  } catch (e) {
    console.error('Error fetching word:', e)
  }
  return null
}

// --- HTML escape ---
function esc(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

// --- Main handler ---
Deno.serve(async (req: Request) => {
  const url = new URL(req.url)
  const word = url.searchParams.get('word')

  if (!word) {
    return Response.redirect(APP_URL, 302)
  }

  const shareUrl = APP_URL + '#' + encodeURIComponent(word)

  // Non-crawler: redirect to app
  const userAgent = req.headers.get('user-agent') || ''
  if (!isCrawler(userAgent)) {
    return Response.redirect(shareUrl, 302)
  }

  // Crawler: fetch word and serve OG HTML
  const palabra = await fetchWord(word)
  if (!palabra) return Response.redirect(APP_URL, 302)

  const title = 'DiccioPeques - ' + palabra.palabra
  const categoria = palabra.categoria || ''
  const definicion = (palabra.definiciones && palabra.definiciones.length > 0)
    ? palabra.definiciones[0].texto
    : ''
  const description = palabra.palabra + ' (' + categoria + '): ' + definicion
  const canonicalUrl = FUNCTION_URL + '?word=' + encodeURIComponent(palabra.palabra)
  // PNG image generated by separate og-image function
  const imageUrl = OG_IMAGE_URL + '?word=' + encodeURIComponent(palabra.palabra)

  const html = `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>

  <meta property="og:type" content="article">
  <meta property="og:title" content="${esc(title)}">
  <meta property="og:description" content="${esc(description)}">
  <meta property="og:image" content="${imageUrl}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="${esc(title)}">
  <meta property="og:url" content="${esc(canonicalUrl)}">
  <meta property="og:site_name" content="DiccioPeques">
  <meta property="og:locale" content="es_ES">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${esc(title)}">
  <meta name="twitter:description" content="${esc(description)}">
  <meta name="twitter:image" content="${imageUrl}">
  <meta name="twitter:image:alt" content="${esc(title)}">
</head>
<body>
  <h1>${esc(palabra.palabra)}</h1>
  <p>${esc(description)}</p>
</body>
</html>`

  return new Response(html, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'public, s-maxage=3600'
    }
  })
})
